#coding:utf-8
from random import choice
def course_func(d):
    list1 = list(d.keys())
    list1.remove(u'tag')
    list1.remove(u'Q')
    list1.remove(u'func')
    key1 = choice(list1)
    key2 = choice(list1)
    key3 = choice(list1)
    return u'姚班的课程有{0}任教的{1}，{2}任教的{3}，{4}任教的{5}等等'.format( d[key1], key1, d[key2], key2, d[key3], key3)

def course_q(d):
    list1 = list(d.keys())
    list1.remove(u'tag')
    list1.remove(u'Q')
    list1.remove(u'func')
    str0 = u"课程列表如下\t\n"
    str1 = u"， \n".join(list1)
    return {u'str':u'你想了解所有课程吗？',
            u'yes_prompt':str0 + str1,
            u'yes_keyword':None,
            u'no':None}

course = [
{u'tag':[u'课程',u'教师',u'姚班'],
 u'func': course_func,
 u'计算机入门':u'黄隆波',
 u'计算机应用数学':u'John Steinberger',
 u'程序设计与算法基础':u'华强胜',
 u'算法设计':u'Periklis Papakonstantinou',
 u'计算理论':u'Iddo Tzameret',
 u'网络科学':u'Thomas Moscibroda',
 u'密码学基础':u'郁昱',
 u'博弈论':u'唐平中',
 u'计算机安全的理论及实践':u'郁昱',
 u'量子信息':u'Giulio Chiribella',
 u'机器学习':u'王立威',
 u'高等计算机图形学':u'胡事民',
 u'操作系统':u'陈渝',
 u'分布式计算':u'陈卫',
 u'机器学习与模式识别':u'徐佳',
 u'信息论与网络编码':u'杨升浩',
 u'计算生物学':u'曾坚阳',
 u'专题训练实践':u'李建',
 u'计算机科学研究实践':u'美国一流大学、清华大学交叉信息研究院教授及各著名研究院所的高级研究主管',
 u'人类和机器的语音交流':u'P.C. Ching, Tan Lee, Helen Meng, William S.-Y. Wang, 徐佳',
 u'Q':course_q}
]

def teacher_name_func(d):
    return u'{0}担任{1}的教授'.format(d[u'教师'], d[u'课程'])


def teacher_q(d):
    return {u'str' : u'你想进一步了解该课程吗？',
            u'yes_prompt': u'',
            u'yes_keyword' : d[u'课程'],
            u'no':None}

teacher_name = [
{u'课程':u'计算机入门',
 u'教师':u'黄隆波',
 u'tag':[u'黄隆波'],
 u'func': teacher_name_func,
 u'Q': teacher_q,
},
{u'课程':u'计算机应用数学',
 u'教师':u'许荣',
 u'tag':[u'许荣'],
 u'func': teacher_name_func,
 u'Q': teacher_q,
},
{u'课程':u'程序设计与算法基础',
 u'教师':u'华强胜',
 u'tag':[u'华强胜'],
 u'func': teacher_name_func,
 u'Q': teacher_q,
},
{u'课程':u'算法设计',
 u'教师':u'Periklis Papakonstantinou',
 u'tag':[u'Periklis Papakonstantinou'],
 u'func': teacher_name_func,
 u'Q': teacher_q,
},
{u'课程':u'计算理论',
 u'教师':u'Iddo Tzameret',
 u'tag':[u'Iddo Tzameret'],
 u'func': teacher_name_func,
 u'Q': teacher_q,
},
{u'课程':u'网络科学',
 u'教师':u'Thomas Moscibroda',
 u'tag':[u'Thomas Moscibroda'],
 u'func': teacher_name_func,
 u'Q': teacher_q,
},
{u'课程':u'密码学基础',
 u'教师':u'郁昱',
 u'tag':[u'郁昱'],
 u'func': teacher_name_func,
 u'Q': teacher_q,
},
{u'课程':u'博弈论',
 u'教师':u'唐平中',
 u'tag':[u'唐平中'],
 u'func': teacher_name_func,
 u'Q': teacher_q,
},
{u'课程':u'计算机安全的理论及实践',
 u'教师':u'郁昱',
 u'tag':[u'郁昱'],
 u'func': teacher_name_func,
 u'Q': teacher_q,
},
{u'课程':u'量子信息',
 u'教师':u'Giulio Chiribella',
 u'tag':[u'Giulio Chiribella'],
 u'func': teacher_name_func,
 u'Q': teacher_q,
},
{u'课程':u'机器学习',
 u'教师':u'王立威',
 u'tag':[u'王立威'],
 u'func': teacher_name_func,
 u'Q': teacher_q,
},
{u'课程':u'高等计算机图形学',
 u'教师':u'胡事民',
 u'tag':[u'胡事民'],
 u'func': teacher_name_func,
 u'Q': teacher_q,
},
{u'课程':u'操作系统',
 u'教师':u'陈渝',
 u'tag':[u'陈渝'],
 u'func': teacher_name_func,
 u'Q': teacher_q,
},
{u'课程':u'分布式计算',
 u'教师':u'陈卫',
 u'tag':[u'陈卫'],
 u'func': teacher_name_func,
 u'Q': teacher_q,
},
{u'课程':u'机器学习与模式识别',
 u'教师':u'徐佳',
 u'tag':[u'徐佳'],
 u'func': teacher_name_func,
 u'Q': teacher_q,
},
{u'课程':u'信息论与网络编码',
 u'教师':u'杨升浩',
 u'tag':[u'杨升浩'],
 u'func': teacher_name_func,
 u'Q': teacher_q,
},
{u'课程':u'计算生物学',
 u'教师':u'曾坚阳',
 u'tag':[u'曾坚阳'],
 u'func': teacher_name_func,
 u'Q': teacher_q,
},
{u'课程':u'专题训练实践',
 u'教师':u'李建',
 u'tag':[u'李建'],
 u'func': teacher_name_func,
 u'Q': teacher_q,
},
{u'课程':u'人类和机器的语音交流',
 u'教师':u'徐佳',
 u'tag':[u'徐佳'],
 u'func': teacher_name_func,
 u'Q': teacher_q,
}
]

def courses_func(d):
    return u'{0}的老师是{1}，我们先来吐槽一下:{3}。\n介绍:{2}'.format(d[u'课程'], d[u'教师'], d[u'介绍'],d[u'吐槽'])

def courses_q(d):
    return {u'str':u'对此我就知道这么多了，你还有什么要问的吗？',
            u'yes_prompt':None,
            u'yes_keyword':None,
            u'no':None}

courses = [
{u'tag':[u'计算机入门',u'黄隆波'],
 u'func': courses_func,
 u'Q': courses_q,
 u'课程':u'计算机入门',
 u'教师':u'黄隆波',
 u'吐槽':u'上来就要用LaTeX',
 u'介绍':u'这门课程研究了计算机科学的基础思想。课程和作业涵盖了许多课题，诸如硬件组织、网络、计算程序、计算限制以及图形等。'},
{u'tag':[u'计算机应用数学',u'许荣'],
 u'func': courses_func,
 u'Q': courses_q,
 u'课程':u'计算机应用数学',
 u'教师':u'John Steinberger',
 u'吐槽':u'作业压力很大，考试真的很水',
 u'介绍':u'该课程面向计算机科学本科专业介绍基本数学技巧，以及这些技巧怎样在计算机科学中应用。'},
{u'tag':[u'程序设计与算法基础',u'华强胜'],
 u'func': courses_func,
 u'Q': courses_q,
 u'课程':u'程序设计与算法基础',
 u'教师':u'华强胜',
 u'吐槽':u'一门课讲完计算机系三门课，神速飞',
 u'介绍':u'本课程计算机软件学的基础课，讲授软件学的最本质内容，并顾及到算法、数据结构和实践等所需的基础。'},
{u'tag':[u'算法设计',u'伯里克利'],
 u'func': courses_func,
 u'Q': courses_q,
 u'课程':u'算法设计',
 u'教师':u'Periklis Papakonstantinou',
 u'吐槽':u'好课，但不同老师重点相去甚远',
 u'介绍':u'本课程介绍算法设计的基础知识，常用算法设计技术，以及算法复杂性的分析。'},
{u'tag':[u'计算理论',u'谭亦东'],
 u'func': courses_func,
 u'Q': courses_q,
 u'课程':u'计算理论',
 u'教师':u'Iddo Tzameret',
 u'吐槽':u'好难，感觉不会再爱了',
 u'介绍':U'本课程介绍计算理论的基础知识，包括有穷自动机理论，正则语言，下推自动机，上下文无关文法，图灵机等，以及可计算性，计算难解性（NP完全性，PSPACE，BPP等）专题。'},
{u'tag':[u'网络科学',u'托马斯'],
 u'func': courses_func,
 u'Q': courses_q,
 u'课程':u'网络科学',
 u'教师':u'Thomas Moscibroda',
 u'吐槽':u'我以为是讲网络的，结果。。',
 u'介绍':u'网络科学（Network Science）是研究利用网络来描述物理、生物和社会现象，建立这些现象的预测模型的科学。'},
{u'tag':[u'密码学基础',u'郁昱'],
 u'func': courses_func,
 u'Q': courses_q,
 u'课程':u'密码学基础',
 u'教师':u'郁昱',
 u'吐槽':u'怎么换人了？我的萌John～～',
 u'介绍':u'本课程的主要目的是介绍现代密码学的一些基本概念。'},
{u'tag':[u'博弈论',u'唐平中'],
 u'func': courses_func,
 u'Q': courses_q,
 u'课程':u'博弈论',
 u'教师':u'唐平中',
 u'吐槽':u'每学期开始都坐满了来自经管人文各种院系的，上了一节课之后就只剩下姚班的了',
 u'介绍':u'本课程是博弈论入门课程，拟从博弈论基础知识着手。课程将介绍纳什均衡等重要概念，旨在引导学生学习演化博弈论、博弈图等更为复杂的课题。'},
{u'tag':[u'计算机安全的理论及实践',u'郁昱'],
 u'func': courses_func,
 u'Q': courses_q,
 u'课程':u'计算机安全的理论及实践',
 u'教师':u'郁昱',
 u'吐槽':u'最水的课，没有之一',
 u'介绍':u'这门课程将主要介绍包括保密性、完整性、可用性等性质在内的信息安全的各个方面，以及实现信息安全所对应的密码学手段。'},
{u'tag':[u'量子信息',u'朱利欧'],
 u'func': courses_func,
 u'Q': courses_q,
 u'课程':u'量子信息',
 u'教师':u'Giulio Chiribella',
 u'吐槽':u'“好课！”，survive的人都这么说，但大多数人都退了',
 u'介绍':u'此课程重点将学生带向量子信息研究的最前沿，包括：量子基础：广义量子演化与量子测量；量子纠缠理论；量子通讯理论：隐形传态及量子密码；量子计算与量子算法；量子纠缠及容错量子计算；量子计算与量子网络的物理实现。'},
{u'tag':[u'机器学习',u'王立威'],
 u'func': courses_func,
 u'Q': courses_q,
 u'课程':u'机器学习',
 u'教师':u'王立威',
 u'吐槽':u'吐槽君今天刚考完，过两天还有deadline，不想吐槽',
 u'介绍':u'机器学习研究的内容是如何使计算机从经验中学习。'},
{u'tag':[u'高等计算机图形学',u'胡事民'],
 u'func': courses_func,
 u'Q': courses_q,
 u'课程':u'高等计算机图形学',
 u'教师':u'胡事民',
 u'吐槽':u'这是一门好课，不解释',
 u'介绍':u'本课程旨在介绍计算机图形学的基本概念、理论、方法和系统，主要内容包括：颜色模型、光照模型、明暗处理、纹理、光线跟踪算法、曲线曲面造型和几何处理等。机器学习研究的内容是如何使计算机从经验中学习。'},
{u'tag':[u'操作系统',u'陈渝'],
 u'func': courses_func,
 u'Q': courses_q,
 u'课程':u'操作系统',
 u'教师':u'陈渝',
 u'吐槽':u'吐槽君还没上过，不过听说相当可怕',
 u'介绍':u'本课程将讲授最基本的操作系统原理。主要内容包括：计算机与操作系统结构，机制与策略，资源管理，多任务系统，内存管理，文件系统，输入输出子系统及设备管理， 通信与网络，保护与安全。本课程要求学生课后积累动手经验。'},
{u'tag':[u'分布式计算',u'陈卫'],
 u'func': courses_func,
 u'Q': courses_q,
 u'课程':u'分布式计算',
 u'教师':u'陈卫',
 u'吐槽':u'吐槽君还没上过，听起来好有意思的感觉啊（误）',
 u'介绍':u'本课程教授分布式计算机系统的基本算法与原理，例如逻辑时钟，协同问题，失效检测，拜占庭移植性协议，分布式加锁，流言协议等。'},
{u'tag':[u'机器学习与模式识别',u'徐佳'],
 u'func': courses_func,
 u'Q': courses_q,
 u'课程':u'机器学习与模式识别',
 u'教师':u'徐佳',
 u'吐槽':u'吐槽君还没上过，不知道怎么样',
 u'介绍':u'本课程将介绍机器学习基本的和最新的方法，并解读其在机器翻译里的应用，旨在为学生灵活运用现有的技术和开发新的算法打下基础。'},
{u'tag':[u'信息论与网络编码',u'杨升浩'],
 u'func': courses_func,
 u'Q': courses_q,
 u'课程':u'信息论与网络编码',
 u'教师':u'杨升浩',
 u'吐槽':u'吐槽君还没上过，不知道怎么样',
 u'介绍':u'本课程介绍Claude Shannon提出的信息论及网络编码。信息论是应用数学和电子工程的分支学科，内容包括信息定量的理论及传送。网络编码是当今信息论研究前沿最受重视的课题之一。'},
{u'tag':[u'计算生物学',u'曾坚阳'],
 u'func': courses_func,
 u'Q': courses_q,
 u'课程':u'计算生物学',
 u'教师':u'曾坚阳',
 u'吐槽':u'吐槽君还没上过，不知道怎么样',
 u'介绍':U'本课程介绍为分析生物数据集（如DNA，RNA，蛋白基因和生物网络）的各种计算问题以及解决这些问题的算法。内容包括：生物序列分析，基因鉴定，监管主题发现，基因组组装，基因组复制和重排，进化理论，聚类算法，无标度网络。'},
{u'tag':[u'专题训练实践',u'李建'],
 u'func': courses_func,
 u'Q': courses_q,
 u'课程':u'专题训练实践',
 u'教师':u'李建',
 u'吐槽':u'吐槽君还没上过，不知道怎么样',
 u'介绍':u'本课程设在大三年级夏季学期，是为大四年级的《计算机科学研究实践》和《综合论文训练》做准备。在该课程中，设置了算法理论、量子网络、复杂性研究、密码及安全、博弈论等专题，并根据学生的兴趣安排进入各专题训练小组进行专题研讨和实践，使学生在实际动手能力、创新思维、团队合作精神等方面得到锻炼和提高。'},
{u'tag':[u'计算机科学研究实践'],
 u'func': courses_func,
 u'Q': courses_q,
 u'课程':u'计算机科学研究实践',
 u'教师':u'美国一流大学、清华大学交叉信息研究院教授及各著名研究院所的高级研究主管',
 u'吐槽':u'吐槽君还没上过，不知道怎么样',
 u'介绍':u'该课程为实践性课程。学生将赴国内外各著名研究院所进行为期一学期的研究实践，每位学生单独跟随各自的导师，参与到具体的、目前理论计算机领域最前沿的研究项目中去，进行研究型开发研讨等实践活动。'},
{u'tag':[u'人类和机器的语音交流',u'徐佳'],
 u'func': courses_func,
 u'Q': courses_q,
 u'课程':u'人类与机器的语音交流',
 u'教师':u'P.C. Ching, Tan Lee, Helen Meng, William S.-Y. Wang, 徐佳',
 u'吐槽':u'啊，人类与机器的语音交流！',
 u'介绍':u'该课程涉及：语言的功能和分类；中文语言及方言；言语产生；言语感知；语音系统；语音信号处理；时频信号分析；语音识别；语音合成；说话人识别；语种识别；自然语言理解；对话系统；语音搜索；多模态人机交互；语音翻译系统。'}]

def professors_func(d):
    return u'{0}担任{1}，主要领域是{2}。\t{3}'.format(d[u'姓名'], d[u'职务'], d[u'领域'], d[u'网址'])

professors = [{u'tag':[u'姚期智'],
               u'func':professors_func,
               u'姓名':u'姚期智',
               u'职务':u'院长、教授',
               u'领域':u'算法分析，计算复杂性，通讯复杂性，密码协议，量子计算',
               u'网址':u'http://iiis.tsinghua.edu.cn/zh/show-3819-1.html'},
              {u'tag':[u'Giulio Chiribella'],
               u'func':professors_func,
               u'姓名':u'Giulio Chiribella',
               u'职务':u'副教授',
               u'领域':u'Quantum Information Theory, Quantum Foundations, and Mathematical Physics',
               u'网址':u'http://iiis.tsinghua.edu.cn/zh/giulio/'},
              {u'tag':[u'华强胜'],
               u'func':professors_func,
               u'姓名':u'华强胜',
               u'职务':u'助理教授',
               u'领域':u'网络科学',
               u'网址':u'http://iiis.tsinghua.edu.cn/zh/qshua/'},
              {u'tag':[u'黄隆波'],
               u'func':professors_func,
               u'姓名':u'黄隆波',
               u'职务':u'助理教授',
               u'领域':u'随机网络优化，随机学习，低延时信息系统控制理论，数据中心网络',
               u'网址':u'http://www.iiis.tsinghua.edu.cn/~huang/'},
              {u'tag':[u'李建'],
               u'func':professors_func,
               u'姓名':u'李建',
               u'职务':u'助理教授',
               u'领域':u'算法设计与分析，数据库，在线学习与优化，随机优化与组合优化',
               u'网址':u'http://iiis.tsinghua.edu.cn/~jianli/'},
              {u'tag':[u'Periklis Papakonstantinou'],
               u'func':professors_func,
               u'姓名':u'伯里克利/Periklis A. Papakonstantinou',
               u'职务':u'助理教授',
               u'领域':u'计算复杂性和密码学',
               u'网址':u'http://iiis.tsinghua.edu.cn/~papakons/'},
              {u'tag':[u'John Steinberger'],
               u'func':professors_func,
               u'姓名':u'许荣/John Steinberger',
               u'职务':u'助理教授',
               u'领域':u'密码学、复杂性理论和组合数论',
               u'网址':u'http://iiis.tsinghua.edu.cn/~john'},
              {u'tag':[u'唐平中'],
               u'func':professors_func,
               u'姓名':u'唐平中',
               u'职务':u'助理教授',
               u'领域':u'人工智能，多主体系统，电子商务，计算经济学，博弈论，机制设计',
               u'网址':u'http://iiis.tsinghua.edu.cn/pingzhongtang/'},
              {u'tag':[u'Iddo Tzameret'],
               u'func':professors_func,
               u'姓名':u'谈亦东/Iddo Tzameret',
               u'职务':u'助理教授',
               u'领域':u'计算理论、计算复杂性、逻辑和组合论、论证复杂性、可满足性和代数复杂性',
               u'网址':u'http://iiis.tsinghua.edu.cn/~tzameret/'},
              {u'tag':[u'Andrew Wan'],
               u'func':professors_func,
               u'姓名':u'温子刚/Andrew Wan',
               u'职务':u'助理教授',
               u'领域':u'计算复杂性，计算学习理论，密码的基础学',
               u'网址':u'http://iiis.tsinghua.edu.cn/~atw12'},
              {u'tag':[u'徐佳'],
               u'func':professors_func,
               u'姓名':u'徐佳',
               u'职务':u'助理教授',
               u'领域':u'人工智能，机器学习，机器翻译',
               u'网址':u'http://www.iiis.tsinghua.edu.cn/~xu'},
              {u'tag':[u'徐葳'],
               u'func':professors_func,
               u'姓名':u'徐葳',
               u'职务':u'助理教授',
               u'领域':u'分布式系统，云计算，系统监控与调试，大数据，数据中心网络',
               u'网址':u'http://iiis.tsinghua.edu.cn/~weixu'},
              {u'tag':[u'杨升浩'],
               u'func':professors_func,
               u'姓名':u'杨升浩',
               u'职务':u'助理教授',
               u'领域':u'信息理论，网络编码，编码理论和通信网络',
               u'网址':u'http://iiis.tsinghua.edu.cn/~shenghao/'},
              {u'tag':[u'曾坚阳'],
               u'func':professors_func,
               u'姓名':u'曾坚阳',
               u'职务':u'助理教授 ',
               u'领域':u'计算生物学, 机器学习, 大数据',
               u'网址':u'http://iiis.tsinghua.edu.cn/zengjy/'},
              {u'tag':[u'王永才'],
               u'func':professors_func,
               u'姓名':u'王永才',
               u'职务':u'助理研究员',
               u'领域':u'compressive sensing, smart grid, real-time learning, data center network',
               u'网址':u'http://iiis.tsinghua.edu.cn/~yongcai/'},
              {u'tag':[u'胡事民'],
               u'func':professors_func,
               u'姓名':u'胡事民',
               u'职务':u'兼职教授',
               u'领域':u'计算机图形学',
               u'网址':u'http://cs.tsinghua.edu.cn/web/WorkersDetail.aspx?Workerid=109'},
              {u'tag':[u'Thomas Moscibroda'],
               u'func':professors_func,
               u'姓名':u'Thomas Moscibroda',
               u'职务':u'兼职教授',
               u'领域':u'网络科学',
               u'网址':u'http://research.microsoft.com/en-us/um/people/moscitho/'},
]

def history_func(d):
    return u'于{0},{1}'.format(d[u'时间'], d[u'事件'])

def history_q(d):
    return {u'str':u'你还想了解其他历史吗？',
            u'yes_prompt':None,
            u'yes_keyword':u'历史',
            u'no':None}

def history1_func(d):
    ss = u'2005年' + u'创办了软件科学实验班(后改为计算机科学实验班，即姚班)'+ u';\n'
    ss += u'2005年' + u'理论计算机科学研究中心（ITCS）成立' + u'\n'
    ss +=  u'2009年4月' + u'将“软件科学实验班”更名为“计算机科学实验班”，这个班也被清华师生亲切地称为“姚班”。' + u'\n'
    ss +=  u'2010年' + u'12月，清华大学交叉信息研究院成立' + u'\n'
    ss +=  u'2011年' + u'量子信息中心成立'
    return ss

def history1_q(d):
    return {u'str':u'我就知道这么多了，还想知道更多的吗？',
            u'yes_prompt':u'登录下面的网页吧\n\thttp://iiis.tsinghua.edu.cn/zh/list-346-1.html',
            u'yes_keyword':None,
            u'no':None}

history = [
{u'tag':[u'历史'],
 u'func':history1_func,
 u'Q': history1_q,
}, 
{u'tag':[u'成立',u'计算机科学实验班'],
 u'func':history_func,
 u'Q':history_q,
 u'创办者':u'姚期智',
 u'时间':u'2005年',
 u'事件':u'创办了软件科学实验班(后改为计算机科学实验班，即姚班)'},
{u'tag':[u'改名',u'姚班'],
 u'func':history_func,
 u'Q':history_q,
 u'时间':u'2009年4月',
 u'事件':u'将“软件科学实验班”更名为“计算机科学实验班”，这个班也被清华师生亲切地称为“姚班”。'},
{u'tag':[u'理论计算机科学研究中心',u'成立'],
 u'func':history_func,
 u'Q':history_q,
 u'时间':u'2005年',
 u'事件':u'理论计算机科学研究中心（ITCS）成立'},
{u'tag':[u'交叉信息研究院',u'成立'],
 u'func':history_func,
 u'Q':history_q,
 u'时间':u'2010年',
 u'事件':u'2010年12月，清华大学交叉信息研究院成立'},
{u'tag':[u'量子信息中心', u'成立'],
 u'func':history_func,
 u'Q':history_q,
 u'时间':u'2011年',
 u'事件':u'量子信息中心成立'}
]




translate = {u'课程名':u'课程',
             u'课程':u'课程',
             u'教师':u'教师',
             u'教授':u'教授',
             u'许荣':u'许荣',
             u'John Steinberger':u'许荣',
             u'John':u'许荣',
             u'John Steinberger':u'许荣',
             u'萌约翰':u'许荣',
             u'约翰':u'许荣',
             u'计入门':u'计算机入门',
             u'计算机入门':u'计算机入门',
             u'计应数':u'计算机应用数学',
             u'计算机应用数学':u'计算机应用数学',
             u'华强胜':u'华强胜',
             u'程序设计与算法基础':u'程序设计与算法基础',
             u'程设':u'程序设计与算法基础',
             u'算设':u'算法设计',
             u'算法设计':u'算法设计',
             u'Papa':u'伯里克利',
             u'Periklis Papakonstantinou':u'伯里克利',
             u'Periklis':u'伯里克利',
             u'Periklis A. Papakonstantinou':u'伯里克利',
             u'Iddo Tzamert':u'谈亦东',
             u'Iddo':u'谈亦东',
             u'谈亦东':u'谈亦东',
             u'计算理论':u'计算理论',
             u'网络科学':u'网络科学',
             u'网科':u'网络科学',
             u'Thomas':u'托马斯',
             u'Thomas Moscibroda':u'托马斯',
             u'密码学基础':u'密码学基础',
             u'密码学':u'密码学基础',
             u'郁昱':u'郁昱',
             u'博弈论':u'博弈论',
             u'唐平中':u'唐平中',
             u'计算机安全的理论及实践':u'计算机安全的理论及实践',
             u'量子信息':u'量子信息',
             u'朱利欧':u'朱利欧',
             u'Giulio':u'朱利欧',
             u'Giulio Chiribella':u'朱利欧',
             u'机器学习':u'机器学习',
             u'王立威':u'王立威',
             u'高等计算机图形学':u'高等计算机图形学',
             u'计算机图形学':u'计算机图形学',
             u'胡事民':u'胡事民',
             u'操作系统':u'操作系统',
             u'操统':u'操作系统',
             u'陈渝':u'陈渝',
             u'分布式计算':u'分布式计算',
             u'分布式':u'分布式计算',
             u'机器学习与模式识别':u'机器学习与模式识别',
             u'徐佳':u'徐佳',
             u'信息论与网络编码':u'信息论与网络编码',
             u'杨升浩':u'杨升浩',
             u'计算生物学':u'计算生物学',
             u'曾坚阳':u'曾坚阳',
             u'专题训练实践':u'专题训练实践',
             u'李建':u'李建',
             u'计算机科学研究实践':u'计算机科学研究实践',
             u'人类和机器的语音交流':u'人类和机器的语音交流',
             u'介绍':u'介绍',
             u'吐槽':u'吐槽',
             u'职务':u'职务',
             u'温子刚':u'温子刚',
             u'Andrew Wan':u'温子刚',
             u'王永才':u'王永才',
             u'兼职教授':u'兼职教授',
             u'姚班':u'姚班',
             u'计算机科学实验班':u'姚班',
             u'理论计算机科学研究中心':u'理论计算机科学研究中心',
             u'交叉信息研究院':u'交叉信息研究院',
             u'叉院':u'交叉信息研究院',
             u'量子计算':u'量子信息',
             u'量子信息':u'量子信息',
             }

database = professors + course + teacher_name + courses + history